@echo off
echo [+] Deleting Sysmon folder...
rmdir /Q /S C:\ProgramData\sysmon
echo [+] Uninstalling Sysmon driver...
sysmon64.exe -u
echo [+] Deleting Auto Task...
SchTasks /Delete /TN Update_Sysmon_Rules /F