@echo off
echo [+] Warning : run this script off the install directory
echo [+] Uninstalling Sysmon driver...
sysmon64.exe -u force
echo [+] Deleting Sysmon folder...
rmdir /Q /S C:\ProgramData\sysmon
echo [+] Deleting Auto Task...
SchTasks /Delete /TN Update_Sysmon_Rules /F